### ISSUE TITLE
Anstataŭi Google Maps per OSM

### ISSUE THREAD

**Issue by picsi** [shayani/eventaservo#6]
Kiel dirite en Telegram, estus pli bone uzi OSM pro ĝia libereco kaj komunuma spirito. OSM jam estas uzata en la ĉefa mapo, sed ankoraŭ ne por la eventaj paĝoj, ekzemple: https://eventaservo.org/eventoj/F735126-0hppAr18

**Comment by shayani** [comment]
Tiu funkcio estas preta per la commit https://github.com/shayani/eventaservo/commit/975ac0ad1a41e001d066d12f9bd3c352e365e543
